application: test-python
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: helloworld.application


libraries:                                                                      
- name: jinja2                                                                  
  version: latest 
- name: markupsafe                                                              
  version: latest
- name: MySQLdb                                                                  
  version: latest 
